### ISSUE TITLE
Build fails creating a new vRO XML-Based project

### ISSUE THREAD

**Issue by nmshadey** [vmware/vrealize-developer-tools#32] opened 2019-06-13 13:01 UTC
### Description

I get the following error when trying to create a new vRO XML-Based project.

[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
Downloading from central: http://10.1.10.32:8081/artifactory/libs-release/com/package-xml-archetype/1/package-xml-archetype-1.pom
Downloading from central-snapshots: http://10.1.10.32:8081/artifactory/libs-snapshot/com/package-xml-archetype/1/package-xml-archetype-1.pom
[WARNING] The POM for com:package-xml-archetype:jar:1 is missing, no dependency information available

This dependency is located at '/com/vmware/pscoe/o11n/archetypes/package-xml-archetype/1.5.11/', so not sure why it's trying to locate it at 'com'

### Steps to Reproduce

1. CTRL+SHIFT+P -> Select 'vRealize: New Project'
2. Select 'vRO XML-Based' project
3. Complete remaining steps

**Expected behavior:** [What you expect to happen]
New project to be created.

**Actual behavior:** [What actually happens]
Build fails.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

#### Client
- vRealize Developer Tools Version: 2.0.2
- vRealize Build Tools Version: 1.5.11
- VSCode Version: 1.31.1
- OS Version: Windows 10

#### Server
- vRealize Automation Version: 7.5
- vRealize Orchestrator Version: 7.5

**Comment by nmshadey** [comment] 2019-06-14 10:50
I tried this again today, and for some reason it worked and the artifact was downloaded from the correct location. I can't explain why this happened the first time but I will try and see if I can re-produce the issue.

**Comment by nblagoev** [comment] 2019-06-14 10:56
OK, please enable debug logging and if you manage to reproduce the issue, attach the logs from the vRealize Developer Tools output pane.

To enable debug log, add `"vrdev.log": "debug"` in your settings.json.

**Comment by nblagoev** [comment] 2019-09-08 09:11
Closing the issue, as it looks like maven hiccup that can't be reproduced anymore.

**Closed by nblagoev** 2019-09-08 09:11 UTC
Labels: type:bug
