### ISSUE TITLE
Hints plugin doesn't work with maven encrypted passwords and basic authentication in settings.xml

### ISSUE THREAD

**Issue by mgovedarov** [vmware/vrealize-developer-tools#53] opened 2019-11-27 15:10 UTC
### Description

When using maven password encryption in settings.xml only vra authentication honours the <server> definition. When authentication is set to basic the hints plugin reports an error: missing vro.username.

### Steps to Reproduce

1. Add <server> section to settings.xml.
2. Add <vro.serverId>reference in the profile properties.
3. Have <vro.auth>basic</vro.auth>
4. Trigger vRO hints collection

**Expected behavior:** Hints are collected from vRO

**Actual behavior:** Error message: Missing vro.username.

**Reproduces how often:** Always

#### Client

-   vRealize Developer Tools Version:
-   vRealize Build Tools Version:
-   VSCode Version:
-   OS Version:

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version:

**Comment by nblagoev** [comment] 2020-01-12 15:14
Duplicate of #33

**Closed by nblagoev** 2020-01-12 15:14 UTC
Labels: status:duplicate, type:bug
